### ISSUE TITLE
Handling UTF-8 values

### ISSUE THREAD

**Issue by ghost** [bnoguchi/redis-node#13]
Hi 

I have issue with saving / receiving utf-8 encoded characters.

// See ./examples/tour.js
var sys = require("sys");
var redis = require("redis-node");
var client = redis.createClient();    // Create the client
client.select(2);                     // Select database 2

// Assign the string "world" to the "hello" key.
// You can provide a callback to handle the response from Redis
// that gets asynchronously run upon seeing the response.
client.set("hello", "АБВГДЕЁЖЗИЙКЛМНЭЮЯ 你好 大红袍", function (err, status) {
  if (err) throw err;
  console.log(status); // true
});

// We may or may not be connected yet, but that's ok, since
// the client queues up any commands.

// Close the connection
setTimeout( function () {
    client.close();
}, 1000);

This script produce: 

node k.js 
true

/usr/local/lib/node/.npm/redis-node/0.2.8/package/lib/client.js:270
        commandName = commandForReply.commandName;
                                     ^
TypeError: Cannot read property 'commandName' of undefined
    at Client.handleReply (/usr/local/lib/node/.npm/redis-node/0.2.8/package/lib/client.js:270:38)
    at Client.<anonymous> (native)
    at Client.emit (events.js:42:17)
    at Client.handleData (/usr/local/lib/node/.npm/redis-node/0.2.8/package/lib/client.js:241:18)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:42:17)
    at Socket._onReadable (net.js:618:14)
    at IOWatcher.onReadable [as callback](net.js:156:10)

I think some issues with byte length vs utf-8 character length.

Can you have a look?

Thanks

**Comment by bnoguchi** [comment]
Check you inbox

**Comment by bnoguchi** [comment]
This should fix it in the client code example you provided:

```
// See ./examples/tour.js
var sys = require("sys");
var redis = require("redis-node");
var client = redis.createClient(); // Create the client
client.select(2); // Select database 2

// Assign the string "world" to the "hello" key.
// You can provide a callback to handle the response from Redis
// that gets asynchronously run upon seeing the response.
var specialChars = "АБВГДЕЁЖЗИЙКЛМНЭЮЯ 你好 大红袍";
var buf = new Buffer(64)
  , size = buf.write(specialChars, 0, "utf8")
  , input = buf.slice(0, size);
client.set("hello", input, function (err, status) {
    if (err) throw err;
    console.log(status); // true
}); 
client.get('hello', function (err, str) {
  console.log(str);
  console.log(str === specialChars);
}); 

// We may or may not be connected yet, but that's ok, since // the client queues up any commands.

// Close the connection
setTimeout( function () {
    client.close();
}, 1000);
```

I'll be rolling out support for this being natively built in as an option.

**Comment by ghost** [comment]
Thanks man for quick response.

**Comment by bnoguchi** [comment]
This is now supported in the newest version of redis-node, which now works with node 0.4.0 (the just released latest stable). What this means is you don't have to handle converting the utf8 strings to Buffers yourself, so no special handling of strings needs to happen in your code.

**Comment by ghost** [comment]
Hi Brian

Unfortunately after updates of node and redis-node
I still cannot get what I set before:

SET [АБВГДЕЁЖЗИЙКЛМНЭЮЯ 你好 大红袍 ]
GOT [АБВГДЕЁЖЗИЙКЛМНЭЮЯ 你好 大红]
false

few bytes missing.

Boris

**Comment by bnoguchi** [comment]
Can you send me a gist with the code that's failing? What system/os are you using? I just tried the following, which works:
    // See ./examples/tour.js
    var sys = require("sys");
    var redis = require("redis-node");
    var client = redis.createClient(); // Create the client
    client.select(2); // Select database 2

```
// Assign the string "world" to the "hello" key.
// You can provide a callback to handle the response from Redis
// that gets asynchronously run upon seeing the response.
var specialChars = "АБВГДЕЁЖЗИЙКЛМНЭЮЯ 你好 大红袍";
var input = specialChars;
client.set("hello", input, function (err, status) {
    if (err) throw err;
    console.log(status); // true
}); 
client.get('hello', function (err, str) {
  console.log(str);
  console.log(str === specialChars);
}); 

// We may or may not be connected yet, but that's ok, since // the client queues up any commands.

// Close the connection
setTimeout( function () {
    client.close();
}, 1000);
```
